# Generated by Django 4.1.6 on 2023-03-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезды рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
